CREATE ROLE agent_runtime LOGIN PASSWORD 'agent_runtime';

GRANT CONNECT ON DATABASE agent_platform TO agent_runtime;
GRANT USAGE ON SCHEMA public TO agent_runtime;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO agent_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO agent_runtime;
